import initScrollSuave from './modules/scroll-suave.js';
import initAnimacaoScroll from './modules/animacao-scroll.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdown from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFetch from './modules/fetch.js';
import initFuncionamento from './modules/functioning.js';
import initBitcoin from './modules/bitcoin.js';

initModal();
initScrollSuave();
initAnimacaoScroll();
initAccordion();
initTabNav();
initTooltip();
initDropdown();
initMenuMobile();
initFetch();
initFuncionamento();
initBitcoin();